@startuml
!pragma layout smetana

!include ../diagram.styles.puml

autonumber

box "Consumer"
participant "Client" as CC
participant "Control Plane" as CCP
participant "Data Plane" as CDP
end box

box "Provider"
participant "Control Plane" as PCP
participant "Data Plane" as PDP
end box

CC -> CCP: <color:red> Initiate
group #F3F7FF Transfer Process Management
CCP -> CDP: Provision
CCP -> PCP: Transfer request
PCP -> PDP: Provision
PCP -> PDP: Create EDR
CCP <- PCP: Transfer started
end
CCP -> CC: <color:red> Callback EDR

group #E3F7FF Data Transfer
CC -> PDP: <color:red> Request data using EDR
CC <- PDP: Response
end


@enduml